export const TOGGLE = "TOGGLE";
export const DELETEONEITEM = "DELETEONEITEM";
export const ADDONEITEM = "ADDONEITEM";
export const CHANGESHOWSTATUS = "CHANGESHOWSTATUS";
export const CHANGEFILTERVALUE = "CHANGEFILTERVALUE";
export const CHANGETHEMECOLOR = "CHANGETHEMECOLOR";
